default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: database
  port: 3306
  username: <%= ENV.fetch('MYSQL_USER') {"root"} %>
  password: <%= ENV.fetch('MYSQL_PASSWORD') {"password"} %>
  socket: /tmp/mysql.sock


production:
  <<: *default
  database: <%= ENV.fetch('MYSQL_DATABASE') {"todo_production"} %>
